apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  project: default
  source:
    path: argocd-apps/
    repoURL: https://alexfiz.github.io/project/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true